services:
    zco_twitter.event_listener:
        class: Zco\Bundle\TwitterBundle\EventListener\EventListener
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_subscriber }
    
    zco_twitter.twitter:
        class: Zco\Bundle\TwitterBundle\Service\Twitter
        arguments: ['http://api.twitter.com/1.1/', 'http://api.twitter.com/oauth/', ['%twitter_api_key%', '%twitter_api_secret%']]