services:
    zco_doctrine1.models_builder:
        class: Zco\Bundle\Doctrine1Bundle\Builder\ModelsBuilder
        arguments: [@kernel]
    
    zco_doctrine1.models_cache_warmer:
        class: Zco\Bundle\Doctrine1Bundle\CacheWarmer\ModelsCacheWarmer
        arguments: [@zco_doctrine1.models_builder]
        tags:
            - { name: kernel.cache_warmer }
    
    zco_doctrine1.adapter.pdo:
        class:     Zco\Bundle\Doctrine1Bundle\Adapter\PDOAdapter
        arguments: ['mysql:dbname=%database.base%;host=%database.host%', '%database.username%', '%database.password%']
        calls:
            - [setDebug, [%kernel.debug%]]
            - [exec, ['SET NAMES utf8']]
    
    zco_doctrine1.data_collector:
        class: Zco\Bundle\Doctrine1Bundle\DataCollector\DoctrineDataCollector
        tags:
            - { name: data_collector, template: "ZcoDoctrine1Bundle::collector", id: doctrine1 }
    
    zco_core.pagination_listener:
        class: Zco\Bundle\Doctrine1Bundle\EventListener\PaginationListener
        tags:
            - { name: kernel.event_subscriber }

    zco_doctrine1.form.type_guesser.orm:
        class: Zco\Bundle\Doctrine1Bundle\Form\DoctrineOrmTypeGuesser
        tags:
            - { name: form.type_guesser }
        
    zco_doctrine1.form.type.entity:
        class: Zco\Bundle\Doctrine1Bundle\Form\Type\EntityType
        tags:
            - { name: form.type, alias: entity }
    
    zco_doctrine1.migrations.configuration:
        class: Zco\Bundle\Doctrine1Bundle\Migrations\Configuration\Configuration
        arguments: [%kernel.root_dir%/../data/migrations, @service_container]

#    zco_doctrine1.orm.validator.unique:
#        class: Zco\Bundle\Doctrine1Bundle\Validator\Constraints\UniqueEntityValidator
#        tags:
#            - { name: validator.constraint_validator, alias: zco_doctrine1.orm.validator.unique }
