msg:
    1:  'Le sondage a bien été ajouté, vous pouvez maintenant lui ajouter des questions.'
    2:  Le sondage a bien été modifié.
    3:  Le sondage a bien été supprimé
    4:  Votre vote a bien été pris en compte. Merci de votre participation !
    5:  Impossible de voter car vous avez déjà voté.
    6:  Vous ne pouvez plus voter car le sondage est fermé.
    7:  Ce sondage n'existe pas.
    8:  La question a bien été ajoutée.
    9:  La question a bien été modifiée.
    10: La question a bien été supprimée.
    11: Cette question n'existe pas.
    12: Votre choix n'est pas valide.
    13: La question spécifiée est invalide.
    14: Vous n'avez pas le droit de voter blanc sur cette question.
    15: Vous devez respecter le nombre de choix indiqué.
    16: Vous ne pouvez pas laisser un message vide.
    17: La question a bien été montée.
    18: La question a bien été descendue.
    19: Impossible de monter la question car elle est déjà en haut.
    20: Impossible de descendre la question car elle est déjà en bas.
    21: La question spécifiée est invalide.