options:
  collate: utf8_unicode_ci
  charset: utf8

Categorie:
  tableName: zcov2_categories
  columns:
    cat_id:              { type: integer(11), primary: true, autoincrement: true, name: cat_id as id }
    cat_nom:             { type: string(100), name: cat_nom as nom }
    cat_gauche:          { type: integer(11), name: cat_gauche as gauche }
    cat_droite:          { type: integer(11), name: cat_droite as droite }
    cat_niveau:          { type: integer(11), name: cat_niveau as niveau }
    cat_description:     { type: string(), name: cat_description as description }
    cat_keywords:        { type: string(255), name: cat_keywords as keywords }
    cat_url:             { type: string(100), name: cat_url as url }
    cat_nb_elements:     { type: integer(11), name: cat_nb_elements as nb_elements }
    cat_last_element:    { type: integer(11), name: cat_last_element as last_element }
    cat_reglement:       { type: string(), name: cat_reglement as reglement }
    cat_map:             { type: string(), name: cat_map as map }
    cat_map_type:        { type: integer(1), name: cat_map_type as map_type }
    cat_image:           { type: boolean, name: cat_image as image }
    cat_redirection:     { type: string(255), name: cat_redirection as redirection }
    cat_disponible_ciblage: { type: boolean, name: cat_disponible_ciblage as disponible_ciblage }
    cat_ciblage_actions: { type: boolean, name: cat_ciblage_actions as ciblage_actions }
  relations:
    Fiches:              { class: Fiche, local: cat_id, foreign: fiche_id, refClass: FicheCategorie }
    GroupeDroit:         { class: GroupeDroit, local: id, foreign: gd_id_categorie }
