all:
    credentials:  [dictees_voir]
ajouter:
    credentials:  [dictees_ajouter]
valider:
    credentials:  [dictees_publier]
propositions:
    credentials:  [dictees_publier]
repondre:
    credentials:  [dictees_publier]
proposer:
    credentials:  [dictees_proposer]
