options:
  collate: utf8_unicode_ci
  charset: utf8

Auteur:
  tableName: zcov2_auteurs
  columns:
    utilisateur_id:      { type: integer(11), notnull: false }
    nom:                 { type: string(100) }
    prenom:              { type: string(100), notnull: false }
    autres:              { type: string(100), notnull: false }
    description:         { type: string, notnull: false }
  relations:
    Utilisateur:         { local: utilisateur_id, foreign: utilisateur_id }
