msg:
  1:  Ce membre n'existe pas.
  2:  Cette facture n'existe pas.
  3:  Le paiement a bien été indiqué comme ayant été envoyé. Les administrateurs le valideront dès réception.
  4:  La facture a bien été marquée comme étant payée.
  5:  La facture a bien été ajoutée.
  6:  La facture a bien été modifiée.
  7:  Il s'est produit une erreur durant la transmission des informations à Paypal.
  8:  La société n'existe pas.
  9:  Vous devez spécifier une société ou un individu.
  10: La facture a bien été supprimée.
  11: Ce passif n'existe pas.
  12: Le passif a bien été ajouté.
  13: Le passif a bien été modifié.
  14: Le passif a bien été supprimé.
  15: Ce don n'existe pas.
  16: Le don a bien été ajouté.
  17: Le don a bien été validé.
  18: Le don a bien été modifié.
  19: Le don a bien été supprimé.
  20: Votre promesse de don a bien été enregistrée.