msg:
    3: Votre design a bien été changé.
    4: Le design par défaut a bien été remis.
    5: Votre fuseau horaire a été modifié.
    6: Vos préférences de participation au programme de test ont bien été prises en compte.