zco_options_index:
    pattern:   /
    defaults:  { _controller: ZcoOptionsBundle:Default:profile, id: ~ }

zco_options_profile:
    pattern:   /profil/{id}
    defaults:  { _controller: ZcoOptionsBundle:Default:profile, id: ~ }

zco_options_password:
    pattern:   /mot-de-passe/{id}
    defaults:  { _controller: ZcoOptionsBundle:Default:password, id: ~ }

zco_options_email:
    pattern:   /courriel/{id}
    defaults:  { _controller: ZcoOptionsBundle:Default:email, id: ~, hash: ~ }
    requirements:
        id: \d+

zco_options_validateEmail:
    pattern:   /courriel/{hash}
    defaults:  { _controller: ZcoOptionsBundle:Default:email, id: ~ }

zco_options_avatar:
    pattern:   /avatar/{id}
    defaults:  { _controller: ZcoOptionsBundle:Default:avatar, id: ~ }

zco_options_absence:
    pattern:   /absence/{id}
    defaults:  { _controller: ZcoOptionsBundle:Default:absence, id: ~ }

zco_options_preferences:
    pattern:   /preferences/{id}
    defaults:  { _controller: ZcoOptionsBundle:Default:preferences, id: ~ }