imports:
    - { resource: parameters.yml }

framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    translator:      { fallback: fr }
    session:
        auto_start:     true
        default_locale: fr
    templating:
        engines:       ['php', 'twig']
        form:
            resources: 
                - 'ZcoCoreBundle:Form'

zco_vitesse:
    assets:
        -
            name: google-jsapi
            type: js
            inputs: 'https://www.google.com/jsapi'
        -
            name: google-maps
            type: js
            inputs: 'http://maps.google.com/maps?file=api&amp;v=2&amp;key=%gmaps_api_key%' }
        -
            name: aviary-feather
            type: js
            inputs: 'http://feather.aviary.com/js/feather.js'

swiftmailer:
    transport:  zco_core.swiftmailer.mandrill_transport

knp_gaufrette:
    adapters:
        uploads:
            local:   { directory:  %kernel.root_dir%/../web/uploads, create: true }
    filesystems:
            uploads: { adapter: uploads }

knp_paginator:
    template:
        pagination: ZcoCoreBundle:Pagination:sliding.html.twig