imports:
  - { resource: config.yml }

monolog:
    handlers:
        # Décommenter pour activer Sentry.
        #sentry:
        #    type: service
        #    id:   zco_sentry.monolog.handler
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: info

# Décommenter pour activer Sentry.
#zco_sentry:
#    dsn: ''
#    resque: zco-sentry
#    auto_log_stacks: false