msg:
    0: Une erreur interne est survenue.
    1: Vous n'avez pas l'autorisation d'accéder à cette page.
    438: 'Vous ne pouvez pas accéder à ce module : il est en maintenance.'

    # Erreurs génériques
    17: Vous devez remplir tous les champs nécessaires !
    23: Erreur lors de la vérification de l'anti-spam.
    24: Vous devez rentrer une adresse mail valide.

    # Erreurs d'uploads
    191: 'Erreur : fichier trop volumineux pour PHP.'
    193: 'Erreur lors du transfert : réessayer pourrait peut-être résoudre le problème.'
    194: 'Erreur : pas de fichier à uploader ?'
    195: 'Erreur configuration serveur : pas de dossier temporaire.'
    196: 'Erreur serveur : écriture impossible dans le dossier temporaire.'
    197: 'Erreur serveur : transfert bloqué à cause de l''extension.'
    198: 'Erreur serveur : impossible d''enregistrer l''image.'

    # Connexion / déconnexion / inscription
    2: Vous êtes bien déconnecté !
    3: 'Vous ne pouvez vous connecter : vous êtes banni.'
    4: Votre compte n'est pas validé !
    5: Couple pseudo / mot de passe inexistant !
    6: Vous êtes bien connecté !
    25: 'Le mot de passe que vous avez reçu par email a été activé, vous pouvez désormais vous identifier sur le site.'
    26: Erreur lors de l'activation du nouveau mot de passe...
    27: Un email vous a été envoyé à l'adresse indiquée.
    28: L'adresse email est inconnue (ou bien vous n'avez pas encore validé votre compte)...
    181: Votre compte a été activé avec succès. Vous pouvez dès maintenant profiter du site !
    182: 'Soit votre compte est déjà actif, soit le code de confirmation donné est incorrect.'
    183: Vous êtes maintenant inscrit. Votre compte est pour l'instant inactif.<br />N'oubliez pas d'aller valider votre inscription en cliquant sur le lien dans l'email qui vous a été envoyé !
    184: 'Pseudo déjà utilisé, veuillez en choisir un différent !'

    # Options
    88: Le format de la date est invalide.
    124: Les options de navigation ont été modifiées avec succès.
    125: 'Erreur : avatar refusé à cause de son format.'
    126: 'Erreur : avatar refusé à cause de ses dimensions.<br />Dimensions maximales autorisées : 100x100 pixels.'
    127: L'URL indiquée ne pointe pas vers un fichier.
    128: 'Mot de passe trop court : la taille minimale est de 6 caractères.'
    129: 'Valeur incorrecte : les deux mots de passe de correspondent pas.'
    130: Votre mot de passe est incorrect.
    131: Le champ <strong>coordonnées</strong> est vide. Cliquez sur le bouton <strong>Trouver les coordonnées</strong>.
    132: Le profil a bien été modifié.
    233: L'adresse mail a bien été modifiée.
    234: La nouvelle adresse mail est pour l'instant inactive.<br />N'oubliez pas d'aller valider votre inscription en cliquant sur le lien dans l'email qui vous a été envoyé à cette dernière !
    241: La nouvelle adresse mail a bien été validée. Vous recevrez désormais tous les mails du site à cette adresse.
    242: 'L''adresse mail n''est pas valide, ou bien déjà utilisée.'
    243: Le mot de passe a bien été changé.
    244: L'avatar a bien été changé.
    330: L'absence a bien été levée.
    331: Vous devez indiquer une absence valide.
    332: Votre période d'absence a bien été enregistrée.
    482: La date que vous avez saisi n'est pas valide.
    483: L'absence ne peut se terminer avant d'avoir commencé.

    # Membres
    122: Vous n'avez pas spécifié de membre dans l'URL.
    123: Ce membre n'existe pas.
    222: Tous les mots de passe des membres de ce groupe ont bien été changés.
    236: Le compte a bien été validé.
    237: Le compte a bien été dévalidé.
    245: Le compte a bien été supprimé.

    246: 'La sanction a bien pris fin ; le membre a été réintégré dans son groupe d''origine.'
    253: Le membre a bien été sanctionné.
    254: Le pourcentage du membre a bien été changé.
    297: Vous ne pouvez pas avertir un membre de l'équipe.

    238: La demande de changement de pseudo a bien été effectuée !
    239: Vous avez déjà une demande changement de pseudo en cours.
    250: La demande de changement de pseudo a bien été validée.
    251: La demande de changement de pseudo a bien été refusée.
    240: Le pseudo a bien été changé.
    247: 'Vous vouliez <em>changer</em> de pseudo ; vous avez indiqué le même !'
    248: Vous n'avez spécifié aucun changement dans l'url.
    249: Cette demande n'existe pas.
    328: Le titre du membre a bien été modifié.
    340: Les messages de ce membre ont bien été supprimés.
