_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

zco_vitesse:
    resource: "@ZcoVitesseBundle/Resources/config/routing.yml"
    prefix:   /res

_main:
    resource: routing.yml