##  Configuration des autorisations nécessaires pour accéder aux actions.  ##

index:
    credentials:    [[cats_ajouter, cats_editer, cats_supprimer, cats_ordonner]]
image:
    credentials:    [[cats_ajouter, cats_editer, cats_supprimer, cats_ordonner]]
graphique:
    credentials:    [[cats_ajouter, cats_editer, cats_supprimer, cats_ordonner]]
ajouter:
    credentials:    [cats_ajouter]
editer:
    credentials:    [cats_editer]
supprimer:
    credentials:    [cats_supprimer]
