msg:
    1:  Le recrutement a bien été ajouté.
    2:  Le recrutement a bien été édité.
    3:  Le recrutement a bien été supprimé.
    4:  Vous ne pouvez pas modifier une candidature en rédaction.
    164: Votre candidature a bien été envoyée aux administrateurs. Vous serez averti de tout changement par MP.
    231: Votre correction a bien été envoyée aux administrateurs. Vous serez averti de tout changement par MP.
    230: Votre candidature a bien été ajoutée.
    165: Votre candidature a bien été modifiée.
    235: La candidature a bien été éditée.
    232: Votre correction a bien été modifiée.
    203: La candidature a bien été acceptée.
    167: La candidature a bien été refusée.
    168: La candidature a bien été soumise à un test.
    169: La candidature a bien été supprimée.
    226: Vous n'avez pas envoyé de candidature dans l'URL.
    227: Cette candidature n'existe pas.
    228: Vous n'avez pas envoyé de recrutement dans l'URL.
    229: Ce recrutement n'existe pas.
    344: Le désistement de cette candidature a bien été pris en compte.
    345: Vous êtes à présent le correcteur de cette copie.
    346: Cette copie a déjà un correcteur attribué.
    347: Le correcteur de cette copie a bien été supprimé.
    348: Votre commentaire a bien été ajouté.
    252: Ce commentaire n'existe pas.
    349: Vous n'avez pas envoyé de message dans l'URL.
    350: Ce message n'existe pas.
    351: Le message a bien été supprimé.
    352: Le message a bien été modifié.
    479: Cette copie a bien été notée conformément à vos souhaits.
