# Pages de visualisation.
postuler:
    credentials:  [recrutements_postuler]
candidatures_membre:
    credentials:  [recrutements_voir_candidatures]

# Pages de gestion des recrutements.
ajouter:
    credentials:  [recrutements_ajouter]
editer_recrutement:
    credentials:  [recrutements_editer]
supprimer_recrutement:
    credentials:  [recrutements_supprimer]
gestion:
    credentials:  [[recrutements_ajouter, recrutements_editer, recrutements_supprimer, recrutements_voir_candidatures, recrutements_repondre]]

# Pages de gestion des candidatures.
candidature:
    credentials:  [recrutements_voir_candidatures]
noter:
    credentials:  [recrutements_voir_candidatures]
corriger:
    credentials:  [recrutements_attribuer_copie]
desister:
    credentials:  [recrutements_desistement]
editer_candidature:
    credentials:  [recrutements_repondre]
repondre:
    credentials:  [recrutements_repondre]
supprimer_candidature:
    credentials:  [recrutements_supprimer_candidatures]

ajouter_message:
    credentials:  [recrutements_ecrire_shoutbox]
editer_message:
    credentials:  [recrutements_editer_shoutbox]
supprimer_message:
    credentials:  [recrutements_supprimer_shoutbox]
