TwitterCompte:
  tableName: zcov2_twitter_comptes
  columns:
    id:               { type: integer, primary: true }
    dernier_tweet:    { type: integer }
    nom:              { type: string(255) }
    creation:         { type: timestamp }
    par_defaut:       { type: boolean, default: 0 }
    tweets:           { type: integer }
    access_key:       { type: string(255) }
    access_secret:    { type: string(255) }
  relations:
    DernierTweet:     { class: TwitterTweet, local: dernier_tweet, foreign: twitter_id }