msg:
    1: Vous n'avez pas l'autorisation d'accéder à cette page.
    2: Votre message a bien été ajouté.
    3: Le message a bien été modifié.
    4: Erreur de l'interface chaise / clavier.<br />Vous ne pouvez pas déposer de message. Un message toutes les semaines est autorisé.
    5: Le message a bien été supprimé.
    6: Erreur de l'interface chaise / clavier.<br />Ce message n'existe pas.