options:
  collate: utf8_unicode_ci
  charset: utf8

Citation:
  tableName: zcov2_citations
  columns:
    utilisateur_id:          { type: integer(11) }
    auteur_prenom:           { type: string(100) }
    auteur_nom:              { type: string(100) }
    auteur_autres:           { type: string(100) }
    contenu:                 { type: string() }
    date:                    { type: timestamp(25) }
    statut:                  { type: boolean }
  relations:
    Utilisateur:             { local: utilisateur_id, foreign: utilisateur_id }

TagCitation:
  columns:
    tag_id:          { type: integer, primary: true }
    citation_id:     { type: integer, primary: true }
  relations:
    Tag:
      foreignAlias: Citations
    Citation:
      foreignAlias: Tags
