all:
    credentials:  [blog_voir]
ajouter:
    credentials:  [blog_ajouter]
ajouter_commentaire:
    credentials:  [blog_commenter]
brouillons:
    credentials:  [blog_voir_billets_redaction]
validation:
    credentials:  [blog_voir_historique]
tous_les_commentaires:
    credentials:  [[blog_editer_commentaires, blog_supprimer_commentaires]]
nouveaux_commentaires:
    credentials:  [[blog_editer_commentaires, blog_supprimer_commentaires]]
gestion:
    credentials:  [[blog_editer_valide, blog_supprimer]]
mes_billets:
    credentials:  [blog_ajouter]
propositions:
    credentials:  [blog_voir_billets_proposes]
refus:
    credentials:  [blog_voir_refus]
supprimer_commentaires:
    credentials:  [blog_supprimer_commentaires]
