<?php

/**
 * zCorrecteurs.fr est le logiciel qui fait fonctionner www.zcorrecteurs.fr
 *
 * Copyright (C) 2012 Corrigraphie
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * PubliciteCampagne
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class PubliciteCampagne extends BasePubliciteCampagne
{
    const RUNNING   = 'en_cours';
    const PAUSED    = 'pause';
    const COMPLETED = 'termine';
    const DELETED   = 'supprime';

    public static $etats = array(
        self::RUNNING   => '<span class="vertf">Active</span>',
        self::PAUSED    => '<span class="orange">En pause</span>',
        self::COMPLETED => '<span class="gris">Terminée</span>',
        self::DELETED   => '<span class="rouge">Supprimée</span>',
    );

    public function getTauxClics()
    {
        return $this['nb_affichages'] > 0 ? 100 * $this['nb_clics'] / $this['nb_affichages'] : 0;
    }

    public function getBudgetDepense()
    {
        $ret = 0;
        foreach ($this->Publicites as $pub)
            $ret += $pub->getBudgetDepense();
        return $ret;
    }

    public function getEtatFormat()
    {
        return self::$etats[$this['etat']];
    }
}