zco_ads_index:
    pattern:   /
    defaults:  { _controller: ZcoPubliciteBundle:Default:index }

zco_ads_campaign:
    pattern:   /campagne/{id}
    defaults:  { _controller: ZcoPubliciteBundle:Default:campaign }
    requirements:
        id: \d+

zco_ads_advertisment:
    pattern:   /publicite/{id}
    defaults:  { _controller: ZcoPubliciteBundle:Default:advertisment }
    requirements:
        id: \d+

zco_ads_targeting:
    pattern:   /publicite/{id}/ciblage
    defaults:  { _controller: ZcoPubliciteBundle:Default:editTargeting }
    requirements:
        id: \d+

zco_ads_resetClicks:
    pattern:   /publicite/{id}/raz-clics/{token}/{date}
    defaults:  { _controller: ZcoPubliciteBundle:Default:resetClicks }
    requirements:
        id: \d+

zco_ads_resetDisplays:
    pattern:   /publicite/{id}/raz-affichages/{token}/{date}
    defaults:  { _controller: ZcoPubliciteBundle:Default:resetDisplays }
    requirements:
        id: \d+

zco_ads_owner:
    pattern:   /publicite/{id}/createur
    defaults:  { _controller: ZcoPubliciteBundle:Default:editOwner }
    requirements:
        id: \d+

zco_ads_appearance:
    pattern:   /publicite/{id}/apparence
    defaults:  { _controller: ZcoPubliciteBundle:Default:editAppearance }
    requirements:
        id: \d+

zco_ads_delete:
    pattern:   /campagne/{id}/supprimer
    defaults:  { _controller: ZcoPubliciteBundle:Default:delete }
    requirements:
        id: \d+

zco_ads_new:
    pattern:   /ajouter/{id}
    defaults:  { _controller: ZcoPubliciteBundle:Default:new, id: ~ }
    requirements:
        id: \d+