zco_ads_default:
    resource: "@ZcoPubliciteBundle/Resources/config/routing/default.yml"
    prefix:   /publicite

zco_ads_graph:
    resource: "@ZcoPubliciteBundle/Resources/config/routing/graph.yml"
    prefix:   /publicite

zco_ads_api:
    resource: "@ZcoPubliciteBundle/Resources/config/routing/api.yml"
    prefix:   /_api/publicite