options:
  collate: utf8_unicode_ci
  charset: utf8

Quiz:
  tableName: zcov2_quiz
  columns:
    categorie_id:       { type: integer(2) }
    utilisateur_id:     { type: integer(11) }
    nom:                { type: string(255) }
    description:        { type: string(255) }
    difficulte:         { type: enum, values: [Facile, Moyen, Difficile] }
    date:               { type: timestamp(25) }
    aleatoire:          { type: integer(11) }
    visible:            { type: boolean }
  relations:
    Categorie:          { local: categorie_id, foreign: cat_id }
    Utilisateur:        { local: utilisateur_id, foreign: utilisateur_id }
    Scores:             { class: QuizScore, local: id, foreign: quiz_id, type: many }

QuizQuestion:
  tableName: zcov2_quiz_questions
  columns:
    quiz_id:            { type: integer(11) }
    utilisateur_id:     { type: integer(11) }
    date:               { type: timestamp(25) }
    question:           { type: string() }
    reponse1:           { type: string() }
    reponse2:           { type: string() }
    reponse3:           { type: string() }
    reponse4:           { type: string() }
    reponse_juste:      { type: integer(1) }
    explication:        { type: string() }
  relations:
    Quiz:               { local: quiz_id, foreign: id }
    Utilisateur:        { local: utilisateur_id, foreign: utilisateur_id }

QuizScore:
  tableName: zcov2_quiz_scores
  columns:
    quiz_id:            { type: integer(11) }
    utilisateur_id:     { type: integer(11) }
    note:               { type: integer(2) }
    date:               { type: timestamp(25) }
  relations:
    Quiz:               { local: quiz_id, foreign: id }
    Utilisateur:        { local: utilisateur_id, foreign: utilisateur_id }
 