services:
    zco_user.validator.username:
        class: Zco\Bundle\UserBundle\Validator\Constraints\UsernameValidator
        arguments: [@zco_user.user]
        tags:
            - { name: validator.constraint_validator, alias: zco_user_username }

    zco_user.validator.password:
        class: Zco\Bundle\UserBundle\Validator\Constraints\PasswordValidator
        arguments: [@zco_user.user]
        tags:
            - { name: validator.constraint_validator, alias: zco_user_password }
    
    zco_user.validator.email:
        class: Zco\Bundle\UserBundle\Validator\Constraints\EmailValidator
        arguments: [@zco_user.user]
        tags:
            - { name: validator.constraint_validator, alias: zco_user_email }