msg:
    1: Ce membre n'existe pas.
    2: Ce groupe n'existe pas.
    3: Ce droit n'existe pas.
    4: Le droit de ce groupe a bien été mis à jour.
    5: Les droits ont bien été rechargés.
    6: Le groupe a bien été ajouté.
    7: Le groupe a bien été modifié.
    8: Le groupe a bien été supprimé.
    9: Le membre a bien été changé de groupe.
    10: Le droit a bien été ajouté.
    11: Le droit a bien été modifié.
    12: Le droit a bien été supprimé.