index:
    credentials:  [[groupes_gerer, groupes_changer_droits]]
ajouter:
    credentials:  [groupes_gerer]
editer:
    credentials: [groupes_gerer]
supprimer:
    credentials: [groupes_gerer]

gestion_droits:
    credentials:  [droits_gerer]
ajouter_droit:
    credentials:  [droits_gerer]
editer_droit:
    credentials:  [droits_gerer]
supprimer_droit:
    credentials:  [droits_gerer]

changer_membre_groupe:
    credentials:  [groupes_changer_membre]
droits:
    credentials:  [groupes_changer_droits]
verifier:
    credentials:  [groupes_changer_droits]
recharger_droits:
    credentials:  [droits_recharger]