services:
    zco_sentry.sentry.client:
        class: Zco\Bundle\SentryBundle\Sentry\Client
        arguments: [@service_container]
    
    zco_sentry.monolog.processor.session_user:
        class: Zco\Bundle\SentryBundle\Monolog\SessionUserProcessor
        tags:
            - { name: monolog.processor, method: processRecord }
    
    zco_sentry.monolog.handler:
        class: Zco\Bundle\SentryBundle\Monolog\SentryHandler
        arguments: [@zco_sentry.sentry.client, 300]
                