options:
  collate: utf8_unicode_ci
  charset: utf8

Annonce:
  tableName: zcov2_annonces
  columns:
    id:               { type: integer, primary: true, autoincrement: true }
    utilisateur_id:   { type: integer(11) }
    nom:              { type: string(255), notnull: true }
    date_debut:       { type: timestamp, notnull: true }
    date_fin:         { type: timestamp, notnull: false }
    actif:            { type: boolean, notnull: true, default: '1' }
    poids:            { type: integer, default: 100 }
    contenu:          { type: string, notnull: true }
    nb_clics:         { type: integer, default: 0, notnull: true }
    nb_affichages:    { type: integer, default: 0, notnull: true }
    nb_fermetures:    { type: integer, default: 0, notnull: true }
    aff_pays_inconnu: { type: boolean, default: '1' }
    url_destination:  { type: string(500) }
  actAs:
    Timestampable:
      created:
        name: date
      updated:
        disabled: true
  relations:
     Utilisateur:     { local: utilisateur_id, foreign: utilisateur_id }
     Pays:            { class: Pays, refClass: AnnoncePays, local: annonce_id, foreign: pays_id, type: many }
     Groupes:         { class: Groupe, refClass: AnnonceGroupe, local: annonce_id, foreign: groupe_id, type: many }
     Categories:      { class: Categorie, refClass: AnnonceCategorie, local: annonce_id, foreign: categorie_id, type: many }
     Domaines:        { class: AnnonceDomaine, local: id, foreign: annonce_id, type: many }

AnnonceCategorie:
  tableName: zcov2_annonces_categories
  columns:
    annonce_id:      { type: integer(11), primary: true }
    categorie_id:    { type: integer(11), primary: true }
  relations:
    Annonce:         { local: annonce_id, foreign: id }
    Categorie:       { local: categorie_id, foreign: cat_id }

AnnoncePays:
  tableName: zcov2_annonces_pays
  columns:
    annonce_id:      { type: integer(11), primary: true }
    pays_id:         { type: integer(11), primary: true }
  relations:
    Annonce:         { local: annonce_id, foreign: id }
    Pays:            { local: pays_id, foreign: id }

AnnonceGroupe:
  tableName: zcov2_annonces_groupes
  columns:
    annonce_id:      { type: integer(11), primary: true }
    groupe_id:       { type: integer(11), primary: true }
  relations:
    Annonce:         { local: annonce_id, foreign: id }
    Groupe:          { local: groupe_id, foreign: id }

AnnonceDomaine:
  tableName: zcov2_annonces_domaines
  columns:
    annonce_id:      { type: integer(11), primary: true }
    domaine:         { type: varchar(255), primary: true }
  relations:
    Annonce:         { local: annonce_id, foreign: id }
