UserNewUsername:
    tableName: zcov2_changements_pseudos
    actAs:
        Timestampable:
            created:     { name: changement_date }
            updated:     { name: changement_date_reponse }
    columns:
        changement_id:               { type: integer(4), primary: true, autoincrement: true, name: changement_id as id }
        changement_id_utilisateur:   { type: integer(4), name: changement_id_utilisateur as user_id }
        changement_id_admin:         { type: integer(4), name: changement_id_admin as admin_id }
        changement_ancien_pseudo:    { type: string(255), name: changement_ancien_pseudo as old_username }
        changement_nouveau_pseudo:   { type: string(255), name: changement_nouveau_pseudo as new_username }
        changement_raison:           { type: string, name: changement_raison as reason }
        changement_reponse:          { type: string, name: changement_reponse as response }
        changement_etat:             { type: integer(4), name: changement_etat as status }
    relations:
        User:           { class: Utilisateur, local: user_id }
        Admin:          { class: Utilisateur, local: admin_id }