UserWarning:
    tableName: zcov2_avertissements
    columns:
        averto_id:             { type: integer(11), primary: true, autoincrement: true, name: averto_id as id }
        averto_id_utilisateur: { type: integer(11), notnull: true, name: averto_id_utilisateur as user_id }
        averto_id_admin:       { type: integer(11), name: averto_id_admin as admin_id }
        averto_pourcentage:    { type: integer(1), name: averto_pourcentage as percentage }
        averto_litige:         { type: string(255), name: averto_litige as link }
        averto_date:           { type: timestamp(25), name: averto_date as date }
        averto_raison:         { type: string(), name: averto_raison as reason }
        averto_raison_admin:   { type: string(), name: averto_raison_admin as admin_reason }
    relations:
        User:           { class: Utilisateur, local: user_id, foreign: utilisateur_id }
        Admin:          { class: Utilisateur, local: admin_id, foreign: utilisateur_id }

