UserPreference:
    tableName: zcov2_utilisateurs_preferences
    columns:
        preference_id_utilisateur:           { type: integer(4), primary: true, name: preference_id_utilisateur as user_id }
        preference_afficher_admin_rapide:    { type: boolean, name: preference_afficher_admin_rapide as display_admin_bar }
        preference_beta_tests:               { type: boolean, name: preference_beta_tests as beta_tests }
        preference_activer_email_mp:         { type: boolean, name: preference_activer_email_mp as email_on_mp }
        preference_decalage:                 { type: integer, notnull: true, name: preference_decalage as time_difference }
    relations:
        User:        { class: Utilisateur, local: user_id, foreign: id }