<?php

/**
 * zCorrecteurs.fr est le logiciel qui fait fonctionner www.zcorrecteurs.fr
 *
 * Copyright (C) 2012 Corrigraphie
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * RecrutementCandidature
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     vincent1870 <vincent@zcorrecteurs.fr>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class RecrutementCandidature extends BaseRecrutementCandidature
{
	const REDACTION = 1;
	const ENVOYE = 2;
	const ATTENTE_TEST = 3;
	const TESTE = 4;
	const ACCEPTE = 5;
	const REFUSE = 6;
	const DESISTE = 7;
	
	private static $etats = array(
		self::ENVOYE => 'En attente',
		self::REDACTION => 'En rédaction',
		self::ACCEPTE => '<span class="vertf">Accepté</span>',
		self::ATTENTE_TEST => 'En test',
		self::TESTE=> 'Testé',
		self::REFUSE => '<span class="rouge">Refusé</span>',
		self::DESISTE => '<span class="rouge">Désistée</span>',
	);
	
	public static function getEtats()
	{
		return self::$etats;
	}
	
	public function getEtatAffichage()
	{
		return self::$etats[$this['etat']];
	}
	
	public function correctionPossible()
	{
		return strtotime($this['date_fin_correction']) >= time();
	}
}