services:
    zco_vitesse.resource_manager:
        class: Zco\Bundle\VitesseBundle\Resource\ResourceManager
        arguments:
            - @zco_vitesse.assetic.asset_manager
            - @zco_vitesse.resource_map
            - @router
            - %zco_vitesse.web_dir%
            - %zco_vitesse.combine_assets%
            - %zco_vitesse.debug%
            - @?logger
    
    zco_vitesse.resource_map:
        class: Zco\Bundle\VitesseBundle\Resource\ResourceMap
        arguments: [%zco_vitesse.cache_dir%]
    
    zco_vitesse.assetic.asset_manager:
        class: Assetic\Factory\LazyAssetManager
        arguments: [@zco_vitesse.assetic.factory]
    
    zco_vitesse.assetic.factory:
        class: Assetic\Factory\AssetFactory
        arguments: [%zco_vitesse.web_dir%/../web, %kernel.debug%]
    
    zco_vitesse.javelin:
        class: Zco\Bundle\VitesseBundle\Javelin\Javelin
        arguments: [@zco_vitesse.resource_manager]
    
    zco_core.templating.helper.vitesse:
        class: Zco\Bundle\VitesseBundle\Templating\Helper\VitesseHelper
        arguments: [@zco_vitesse.resource_manager]
        tags:
            - { name: templating.helper, alias: vitesse }

    zco_vitesse.templating.helper.javelin:
        class: Zco\Bundle\VitesseBundle\Templating\Helper\JavelinHelper
        arguments: [@zco_vitesse.javelin]
        tags:
            - { name: templating.helper, alias: javelin }