msg:
    10:  Votre fichier XML est invalide.
    11:  L'encodage du fichier XML est invalide.
    12:  L'en-tête XML du fichier est invalide.
    13:  Le tutoriel a bien été importé.
    
    138: Vous n'avez pas spécifié de tutoriel dans l'URL.
    139: Ce tutoriel n'existe pas ou vous ne vous en occupez pas.
    140: Version du tutoriel corrigé effacée avec succès. Vous pouvez maintenant recommencer la correction du tutoriel.
    141: La correction de ce tutoriel a bien été abandonnée.
    142: Reprise de la correction.
    143: Reprise de la recorrection.
    144: La correction de ce tutoriel est terminée ! Pourquoi voulez-vous le corriger ?
    145: Trop tard ! Quelqu'un l'a pris en correction avant vous !
    146: Trop tard ! Quelqu'un l'a pris en recorrection avant vous !
    147: Vous pouvez maintenant corriger ce tutoriel.
    148: Vous pouvez maintenant recorriger ce tutoriel.
    149: Ce tutoriel a bien été marqué comme corrigé.
    150: Ce tutoriel a bien été marqué comme corrigé. Recorrection demandée.
    151: Le tutoriel a bien été remis dans le circuit de zCorrection.
    152: La soumission est maintenant prioritaire.
    153: La soumission n'est maintenant plus prioritaire.
    154: 'Vous ne pouvez pas modifier cette correction : elle est soit déjà finie, soit non commencée.'
    155: La correction a bien été retirée.
    156: La soumission a bien été supprimée.
    161: Les commentaires ont bien été mis à jour.
    162: L'avancement a bien été mis à jour.
    163: Le tutoriel a bien été refusé.

    185: 'Erreur : fichier refusé à cause d''une extension invalide. Il doit être en .tuto'
    186: 'Erreur : Vous ne pouvez envoyer que 3 tutoriels à la fois à la zCorrection.'
    187: 'Erreur : contenu du fichier incorrect.'
    188: 'Erreur : encodage non supporté...'
    189: Le tutoriel a bien été envoyé à la zCorrection !
    190: 'Erreur impromptue : fichier uploadé, mais non sauvegardé.'

    204: Type de tutoriel inconnu.
    205: La correction de ce tutoriel n'est pas finie.

    294: 'La demande de correction de ce tutoriel a bien été annulée, celui-ci a été supprimé définitivement.'
    295: 'Vous ne pouvez pas annuler la demande de correction de ce tutoriel : elle a déjà débutée. Nous vous invitons à prendre contact avec nous en cas d''impératif.'
    307: Le Site du Zéro a bien reçu le tutoriel !<br />Le Validateur et les auteurs ont reçu un MP.
    308: Une erreur s'est produite lors de la réception du tutoriel par le SdZ.
