commentaires:
    credentials:  [zcorriger]
corriger:
    credentials:  [zcorriger]
exporter:
    credentials:  [zcorriger]
terminer:
    credentials:  [zcorriger]
exporter_sdz:
    credentials:  [zcorriger]

corrections:
    credentials:  [voir_tutos_corriges]
index:
    credentials:  [[zcorriger, voir_tutos_attente]]
gestion:
    credentials:  [[zcorrection_retirer, zcorrection_priorite, zcorrection_editer_tutos]]

voir_mini_tuto:
    credentials:  [[zcorriger, voir_tutos_attente, voir_tutos_corriges, voir_tutos_correction]]
voir_big_tuto:
    credentials:  [[zcorriger, voir_tutos_attente, voir_tutos_corriges, voir_tutos_correction]]
