options:
  collate: utf8_unicode_ci
  charset: utf8

Sondage:
  tableName: zcov2_sondages
  columns:
    utilisateur_id:    { type: integer(11) }
    nom:               { type: string(255) }
    description:       { type: string() }
    date_debut:        { type: timestamp }
    date_fin:          { type: timestamp }
    nb_questions:      { type: integer(4) }
    ouvert:            { type: boolean }
  relations:
    Utilisateur:      { local: utilisateur_id, foreign: utilisateur_id }

SondageQuestion:
  tableName: zcov2_sondages_questions
  columns:
    sondage_id:       { type: integer(11), notnull: true }
    nom:              { type: string(255) }
    nb_votes:         { type: integer(11), default: 0 }
    nb_blanc:         { type: integer(11), default: 0 }
    ordre:            { type: integer(4) }
    libre:            { type: boolean }
    nb_min_choix:     { type: integer(4), default: 1 }
    nb_max_choix:     { type: integer(4), default: 1 }
    obligatoire:      { type: boolean }
    resultats_publics: { type: boolean, default: 1 }
  relations:
    Sondage:          { local: sondage_id, foreign: id, foreignAlias: Questions }

SondageReponse:
  tableName: zcov2_sondages_reponses
  columns:
    question_id:          { type: integer(11), notnull: true }
    question_suivante_id: { type: integer(11), notnull: false }
    nom:                  { type: string(255) }
    nb_votes:             { type: integer(11), default: 0 }
    ordre:                { type: integer(4) }
    question_suivante:    { type: enum, values: [suivante, fin, id] }
  relations:
    Question:             { class: SondageQuestion, local: question_id, foreign: id, foreignAlias: Reponses }
    QuestionSuivante:     { class: SondageQuestion, local: question_suivante_id, foreign: id }

SondageVote:
  tableName: zcov2_sondages_votes
  columns:
    utilisateur_id:   { type: integer(11), notnull: false }
    reponse_id:       { type: integer(11), notnull: false }
    question_id:      { type: integer(11), notnull: true }
    date:             { type: timestamp }
    ip:               { type: integer(11) }
  relations:
    Reponse:          { class: SondageReponse, local: reponse_id, foreign: id }
    Question:         { class: SondageQuestion, local: question_id, foreign: id, foreignAlias: Votes }
    Utilisateur:      { local: utilisateur_id, foreign: utilisateur_id }
    TexteLibre:       { class: SondageTexte, local: id, foreign: vote_id }

SondageTexte:
  tableName: zcov2_sondages_votes_textes
  columns:
    vote_id:          { type: integer(11), primary: true }
    texte:            { type: string() }
  relations:
    Vote:             { class: SondageVote, local: vote_id, foreign: id }
