all:
  credentials:   [aide_voir]

ajouter:
  credentials:   [aide_ajouter]
modifier:
  credentials:   [aide_modifier]
supprimer:
  credentials:   [aide_supprimer]
gestion:
  credentials:   [[aide_ajouter, aide_modifier, aide_supprimer]]