all:
    login_required:  on
    credentials:     [mp_voir]
nouveau_mp_semi_auto:
    credentials:   [mp_voir, mp_envoyer_auto]
marquer_alertes_resolues:
    credentials:   [mp_voir, mp_alertes]
alertes:
    credentials:   [mp_voir, mp_alertes]
alertes:
    credentials:   [mp_voir, mp_signaler]
