<?php

/**
 * Copyright 2012 Corrigraphie
 * 
 * This file is part of zCorrecteurs.fr.
 *
 * zCorrecteurs.fr is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * zCorrecteurs.fr is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with zCorrecteurs.fr. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Annonce
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @author vincent1870 <vincent@zcorrecteurs.fr>
 */
class Annonce extends BaseAnnonce
{
	public function genererHTML()
	{
		return $this->getTable()->genererHTML($this);
	}
	
	public function estAffichable()
	{
		return $this['actif'] && strtotime($this['date_debut']) <= time() && (empty($this['date_fin']) || strtotime($this['date_fin']) >= time());
	}
	
	public function getGroupesId()
	{
		$groupes = array();
		foreach ($this['Groupes'] as $groupe)
		{
			$groupes[$groupe['id']] = $groupe['id'];
		}
		
		return $groupes;
	}
	
	public function getPaysId()
	{
		$pays = array();
		foreach ($this['Pays'] as $p)
		{
			$pays[$p['id']] = $p['id'];
		}
		
		return $pays;
	}
	
	public function getCategoriesId()
	{
		$categories = array();
		foreach ($this['Categories'] as $categorie)
		{
			$categories[$categorie['id']] = $categorie['id'];
		}
		
		return $categories;
	}
	
	public function getDomainesId()
	{
		$domaines = array();
		foreach ($this['Domaines'] as $domaine)
		{
			$domaines[$domaine['domaine']] = $domaine['domaine'];
		}
		
		return $domaines;
	}
	
	
	public function mettreEnCache()
	{
		//$this->refreshRelated('Groupes');
		//$this->refreshRelated('Categories');
		$array = $this->toArray();
		
		//Suppression des données du créateur.
		unset($array['Utilisateur']);
		
		//Mise en forme des tableaux.
		$array['Pays'] = $this->getPaysId();
		$array['Categories'] = $this->getCategoriesId();
		$array['Groupes'] = $this->getGroupesId();
		$array['Domaines'] = $this->getDomainesId();

		Container::getService('zco_core.cache')->set('annonce_details-'.$this['id'], $array, 0);
		
		return $array;
	}
}