options:
  collate: utf8_unicode_ci
  charset: utf8

Dictee:
  tableName: zcov2_dictees
  columns:
    id:                 { type: integer(11), unsigned: true, primary: true, autoincrement: true }
    utilisateur_id:     { type: integer(11) }
    auteur_id:          { type: integer(11), notnull: false }
    etat:               { type: integer(1) }
    difficulte:         { type: integer(1) }
    participations:     { type: integer(11) }
    note:               { type: integer(2) }
    temps_estime:       { type: integer(2) }
    titre:              { type: string(255) }
    source:             { type: string(255) }
    creation:           { type: timestamp(25) }
    edition:            { type: timestamp(25) }
    validation:         { type: timestamp(25) }
    description:        { type: string() }
    texte:              { type: string() }
    indications:        { type: string() }
    commentaires:       { type: string() }
    format:             { type: string(25) }
    icone:              { type: string(255) }

  relations:
    Utilisateur:        { local: utilisateur_id, foreign: utilisateur_id }
    Auteur:             { local: auteur_id, foreign: id }

Dictee_Participation:
  tableName: zcov2_dictees_participations
  columns:
    id:                 { type: integer(11), unsigned: true, primary: true, autoincrement: true }
    dictee_id:          { type: integer(11), unsigned: true }
    utilisateur_id:     { type: integer(11), unsigned: true, notnull: false }
    date:               { type: timestamp(25) }
    fautes:             { type: integer(3) }
    note:               { type: integer(2) }

  relations:
    Dictee:             { local: dictee_id, foreign: id }
    Utilisateur:        { local: utilisateur_id, foreign: utilisateur_id }

DicteeTag:
  tableName: zcov2_dictees_tags
  columns:
    dictee_id:          { type: integer, primary: true }
    tag_id:             { type: integer, primary: true }
  relations:
    Dictee:             { local: dictee_id, foreign: id }
    Tag:                { local: tag_id, foreign: id }
