services:
    zco_forum.event_listener:
        class: Zco\Bundle\ForumBundle\EventListener\EventListener
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_subscriber }