zco_ad_api_editCampaignName:
    pattern:   /campagne/{id}/nom
    defaults:  { _controller: ZcoAdBundle:Api:editCampaignName }
    options:   { expose: true }
    requirements:
      id: \d+
      _method: post

zco_ad_api_editCampaignStatus:
    pattern:   /campagne/{id}/etat
    defaults:  { _controller: ZcoAdBundle:Api:editCampaignStatus }
    options:   { expose: true }
    requirements:
      id: \d+
      _method: post

zco_ad_api_editCampaignDates:
    pattern:   /campagne/{id}/dates
    defaults:  { _controller: ZcoAdBundle:Api:editCampaignDates }
    options:   { expose: true }
    requirements:
      id: \d+
      _method: post

zco_ad_api_editAdStatus:
    pattern:   /publicite/{id}/etat
    defaults:  { _controller: ZcoAdBundle:Api:editAdvertismentStatus }
    options:   { expose: true }
    requirements:
      id: \d+
      _method: post

zco_ad_api_saveClick:
    pattern:   /publicite/{id}/clic
    defaults:  { _controller: ZcoAdBundle:Api:saveClick }
    options:   { expose: true }
    requirements:
      id: \d+
      _method: post
