zco_ad_index:
    pattern:   /
    defaults:  { _controller: ZcoAdBundle:Default:index }

zco_ad_campaign:
    pattern:   /campagne/{id}
    defaults:  { _controller: ZcoAdBundle:Default:campaign }
    requirements:
        id: \d+

zco_ad_advertisment:
    pattern:   /publicite/{id}
    defaults:  { _controller: ZcoAdBundle:Default:advertisment }
    requirements:
        id: \d+

zco_ad_targeting:
    pattern:   /publicite/{id}/ciblage
    defaults:  { _controller: ZcoAdBundle:Default:editTargeting }
    requirements:
        id: \d+

zco_ad_resetClicks:
    pattern:   /publicite/{id}/raz-clics/{token}/{date}
    defaults:  { _controller: ZcoAdBundle:Default:resetClicks }
    requirements:
        id: \d+

zco_ad_resetDisplays:
    pattern:   /publicite/{id}/raz-affichages/{token}/{date}
    defaults:  { _controller: ZcoAdBundle:Default:resetDisplays }
    requirements:
        id: \d+

zco_ad_owner:
    pattern:   /publicite/{id}/createur
    defaults:  { _controller: ZcoAdBundle:Default:editOwner }
    requirements:
        id: \d+

zco_ad_appearance:
    pattern:   /publicite/{id}/apparence
    defaults:  { _controller: ZcoAdBundle:Default:editAppearance }
    requirements:
        id: \d+

zco_ad_delete:
    pattern:   /campagne/{id}/supprimer
    defaults:  { _controller: ZcoAdBundle:Default:delete }
    requirements:
        id: \d+

zco_ad_new:
    pattern:   /ajouter/{id}
    defaults:  { _controller: ZcoAdBundle:Default:new, id: ~ }
    requirements:
        id: \d+