zco_ad_graph_campaigns:
    pattern:   /graphique
    defaults:  { _controller: ZcoAdBundle:Graph:campaigns }
    options:   { expose: true }

zco_ad_graph_advertisment:
    pattern:   /publicite/{id}/graphique
    defaults:  { _controller: ZcoAdBundle:Graph:advertisment }
    options:   { expose: true }
    requirements:
        id: \d+