msg:
    1: Votre recherche ne comporte que des mots de 2 caractères ou moins (qui sont ignorés).
    2: Votre catégorie de recherche est invalide.
    3: La recherche a bien été ajoutée aux favoris.
    4: La recherche a bien été retirée des favoris.