services:
    zco_about.event_listener:
        class: Zco\Bundle\AboutBundle\EventListener\EventListener
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_subscriber }
