#Retient les informations sur toutes les miniatures créées pour une image.
FileThumbnail:
    columns:
        id:                 { type: integer(11), autoincrement: true, primary: true }
        file_id:            { type: integer(11), notnull: false }
        width:              { type: integer(4), notnull: false }
        height:             { type: integer(4), notnull: false }
        size:               { type: integer(4), notnull: true }
        path:               { type: string(255), notnull: true }
    relations:
        File:               { local: file_id }
