all:
    credentials: [tracker_voir]

git:
    credentials: [depot_voir]
roadmap:
    credentials: [roadmap_voir]
todo:
    credentials: [tracker_etre_assigne]
ajouter_projet:
    credentials: [roadmap_gerer]
editer_projet:
    credentials: [roadmap_gerer]
supprimer_projet:
    credentials: [roadmap_gerer]
nouvelle_demande:
    credentials: [tracker_ajouter]
supprimer_reponse:
    credentials: [tracker_supprimer_reponses]
repondre_anomalie:
    credentials: [tracker_repondre]
liste_retours_experience:
    credentials: [evolution_voir_retours]