services:
    zco_evolution.event_listener:
        class: Zco\Bundle\EvolutionBundle\EventListener\EventListener
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_subscriber }