##  Configuration des autorisations nécessaires pour accéder aux actions.  ##

index:
    credentials:   [[citations_ajouter, citations_modifier, citations_supprimer, citations_autoriser]]
ajouter:
    credentials:    [citations_ajouter]
editer:
    credentials:    [citations_modifier]
supprimer:
    credentials:    [citations_supprimer]