zco_blog_api_index:
    pattern:   /
    defaults:  { _controller: ZcoBlogBundle:Api:index, _format: json }

zco_blog_api_category:
    pattern:   /categorie/{id}
    defaults:  { _controller: ZcoBlogBundle:Api:category, _format: json }
    requirements:
        id: \d+

zco_blog_api_article:
    pattern:   /article/{id}
    defaults:  { _controller: ZcoBlogBundle:Api:article, _format: json }
    requirements:
        id: \d+
