all:
    login_required:  true
index:
    credentials:     [ips_voir_bannies]
analyser:
    credentials:     [ips_analyser]
localiser:
    credentials:     [ips_analyser]
membre:
    credentials:     [ips_analyser]
bannir:
    credentials:     [ips_bannir]
doublons:
    credentials:     [ips_analyser]