Auteur:
    config:
        singular:            Auteur
        plural:              Auteurs

    actions:
        _delete:     { label: Supprimer, credentials: [auteurs_modifier] }
        _new:        { label: Ajouter un auteur, credentials: [auteurs_ajouter] }
        _edit:       { label: Modifier, credentials: [auteurs_modifier] }

    form:
        fieldsets:
            NONE:
                display:        [nom, prenom, autres, description]

    list:
        title:              Gestion des auteurs
        description:        |
          Les auteurs peuvent être liés à différentes ressources sur le site, notamment
          les dictées.
        display:            [nom, prenom, autres]
        ordering:           nom
        search_field:       nom
        max_per_page:       50
        object_actions:
            _edit:          ~
            _delete:        ~
        actions:
            _new:           ~

    new:
        title:       Ajouter un auteur

    edit:
        title:       Modifier l'auteur %prenom% %nom%

    delete:
        title:       Supprimer l'auteur %prenom% %nom%
        message:     Voulez-vous vraiment supprimer l'auteur <strong>%prenom% %nom%</strong> ?
