all:
  login_required: true

gestion:
  credentials:   [[publicite_proposer, publicite_voir]]
ajouter:
  credentials:   [publicite_proposer]

propositions:
  credentials:   [[publicite_changer_etat]]
repondre:
  credentials:   [[publicite_changer_etat]]
supprimer_campagne:
  credentials:   [publicite_supprimer]
raz_clics:
  credentials:   [publicite_raz_clics]
raz_affichages:
  credentials:   [publicite_raz_affichages]