#Liste des licences disponibles.
License:
    columns:
        id:                         { type: integer(11), autoincrement: true, primary: true }
        name:                       { type: string(255) }
        logo_url:                   { type: string(255) }
        summary_url:                { type: string(255) }
        fulltext_url:               { type: string(255) }
        keep_author:                { type: boolean }
        keep_same_license:          { type: boolean }
        can_be_modified:            { type: boolean }
        commercial_use_allowed:     { type: boolean }
