msg:
    1: Le mode maintenance a bien été mis à jour.
    2: Le nom d'utilisateur ou le mot de passe est incorrect.
    3: Les changements ont bien été enregistrés.
    7: Le cache a été supprimé avec succès.
    8: Purge des caches effectuée avec succès !
    9: La configuration n'a pas été modifiée.
